# Generated by Django 5.1.1 on 2025-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppApartment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="intermediartionPercent",
        ),
        migrations.RemoveField(
            model_name="user",
            name="status",
        ),
        migrations.AddField(
            model_name="user",
            name="isBuyer",
            field=models.BooleanField(default=True),
        ),
    ]
