# Generated by Django 5.1.1 on 2025-01-22 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppApartment", "0002_remove_user_intermediartionpercent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField(null=True)),
                ("status", models.BooleanField(default=False)),
                ("brokerage", models.BooleanField(default=False)),
                ("price", models.IntegerField()),
                ("city", models.CharField(max_length=20)),
                ("neighborhood", models.CharField(max_length=20)),
                ("street", models.CharField(max_length=20)),
                ("houseNumber", models.IntegerField()),
                ("floor", models.IntegerField()),
                ("rooms", models.IntegerField()),
                (
                    "userId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "apartmentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppApartment.apartment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="message",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("body", models.TextField()),
                (
                    "apartmentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="AppApartment.apartment",
                    ),
                ),
            ],
        ),
    ]
