# Generated by Django 5.1.5 on 2025-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppApartment', '0003_apartment_image_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
